"""Generate the compact slow-planet table the Pine indicator embeds.

Sun and Moon are computed natively in Pine from Meeus series, so they need no table.
Guru, Shani and Rahu move slowly enough (0.083, 0.033 and 0.053 deg/day) that yearly
nodes with linear interpolation stay well inside a degree - far tighter than the
13 deg 20' width of a nakshatra or the 30 deg of a rashi.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from ..astro.ephemeris import graha_positions

SLOW = ["Guru", "Shani", "Rahu"]


def build_table(start_year: int = 1996, end_year: int = 2036, per_year: int = 12) -> pd.DataFrame:
    """Sidereal longitudes of the slow grahas at regular nodes."""
    dates = pd.date_range(f"{start_year}-01-01", f"{end_year}-01-01", freq=f"{365 // per_year}D")
    pos = graha_positions(dates, use_cache=False)
    out = pd.DataFrame(index=dates)
    for g in SLOW:
        out[g] = pos[f"{g}_lon"].to_numpy()
    return out


def _unwrap(series: np.ndarray) -> np.ndarray:
    """Unwrap 0/360 jumps so linear interpolation between nodes is monotone."""
    return np.degrees(np.unwrap(np.radians(series)))


def to_pine(table: pd.DataFrame, var_prefix: str = "cq") -> str:
    """Emit Pine v6 array literals plus a lookup function."""
    jd0 = (table.index[0] - pd.Timestamp("1970-01-01")).total_seconds() / 86400.0 + 2440587.5
    step_days = (table.index[1] - table.index[0]).days

    lines = [
        "// ---------------------------------------------------------------------------",
        "// Slow-graha table: sidereal longitudes at regular nodes, linearly interpolated.",
        f"// Span {table.index[0].date()} to {table.index[-1].date()}, "
        f"{step_days}-day nodes, {len(table)} points per graha.",
        "// Guru/Shani/Rahu move 0.08/0.03/0.05 deg per day, so interpolation error stays",
        "// far below one degree - nakshatra boundaries are 13 deg 20' wide.",
        "// Generated by chandraquant/pine/emit.py - do not hand-edit.",
        "// ---------------------------------------------------------------------------",
        f"{var_prefix}_jd0   = {jd0:.5f}",
        f"{var_prefix}_step  = {step_days}.0",
    ]

    for g in SLOW:
        vals = _unwrap(table[g].to_numpy())
        chunks = ", ".join(f"{v:.3f}" for v in vals)
        lines.append(f"var float[] {var_prefix}_{g.lower()} = array.from({chunks})")

    lines += [
        "",
        f"{var_prefix}_slow(arr, jd) =>",
        f"    float pos = (jd - {var_prefix}_jd0) / {var_prefix}_step",
        "    int n = array.size(arr)",
        "    int i = math.max(0, math.min(n - 2, int(math.floor(pos))))",
        "    float frac = math.max(0.0, math.min(1.0, pos - i))",
        "    float a = array.get(arr, i)",
        "    float b = array.get(arr, i + 1)",
        "    (a + (b - a) * frac) % 360.0",
    ]
    return "\n".join(lines)


def write(path: str | None = None) -> str:
    from ..config import PINE_DIR

    table = build_table()
    text = to_pine(table)
    target = path or (PINE_DIR / "_slow_table.pine")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    return str(target)


if __name__ == "__main__":
    print(write())
